# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pipedrive-ruby 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "pipedrive-ruby".freeze
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jan Schwenzien".freeze, "Waldemar Kusnezow".freeze, "Joel Courtney".freeze]
  s.date = "2025-12-18"
  s.description = "Ruby wrapper for the Pipedrive API".freeze
  s.email = "jan@general-scripting.com".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".devcontainer/Dockerfile",
    ".devcontainer/compose.yaml",
    ".devcontainer/devcontainer.json",
    ".document",
    "CLAUDE.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "V2_MIGRATION_NOTES.md",
    "VERSION",
    "lib/pipedrive-ruby.rb",
    "lib/pipedrive/activity-type.rb",
    "lib/pipedrive/activity.rb",
    "lib/pipedrive/authorization.rb",
    "lib/pipedrive/base.rb",
    "lib/pipedrive/currency.rb",
    "lib/pipedrive/deal-field.rb",
    "lib/pipedrive/deal.rb",
    "lib/pipedrive/file.rb",
    "lib/pipedrive/filter.rb",
    "lib/pipedrive/goal.rb",
    "lib/pipedrive/note.rb",
    "lib/pipedrive/organization-field.rb",
    "lib/pipedrive/organization.rb",
    "lib/pipedrive/permission-set.rb",
    "lib/pipedrive/person-field.rb",
    "lib/pipedrive/person.rb",
    "lib/pipedrive/pipeline.rb",
    "lib/pipedrive/product-field.rb",
    "lib/pipedrive/product.rb",
    "lib/pipedrive/push-notification.rb",
    "lib/pipedrive/role.rb",
    "lib/pipedrive/search-result.rb",
    "lib/pipedrive/stage.rb",
    "lib/pipedrive/user-connection.rb",
    "lib/pipedrive/user-setting.rb",
    "lib/pipedrive/user.rb",
    "pipedrive-ruby.gemspec",
    "test/data/all_deal_fields_body.json",
    "test/data/create_activity_body.json",
    "test/data/create_deal_body.json",
    "test/data/create_note_body.json",
    "test/data/create_organization_body.json",
    "test/data/create_person_body.json",
    "test/data/find_activity_body.json",
    "test/data/find_deal_with_custom_fields_body.json",
    "test/data/find_organization_body.json",
    "test/data/find_person_body.json",
    "test/data/find_user_body.json",
    "test/data/update_deal_body.json",
    "test/helper.rb",
    "test/test_pipedrive_activity.rb",
    "test/test_pipedrive_authentication.rb",
    "test/test_pipedrive_deal.rb",
    "test/test_pipedrive_note.rb",
    "test/test_pipedrive_organization.rb",
    "test/test_pipedrive_person.rb",
    "test/test_v2_abstraction_layer.rb"
  ]
  s.homepage = "https://github.com/GeneralScripting/pipedrive-ruby.git".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.3.27".freeze
  s.summary = "Ruby wrapper for the Pipedrive API".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<httparty>.freeze, [">= 0"])
    s.add_runtime_dependency(%q<json>.freeze, [">= 2.0"])
    s.add_runtime_dependency(%q<multi_xml>.freeze, [">= 0.5.2"])
    s.add_development_dependency(%q<rdoc>.freeze, [">= 4.0"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
    s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_development_dependency(%q<webmock>.freeze, [">= 0"])
    s.add_development_dependency(%q<coveralls>.freeze, [">= 0"])
  else
    s.add_dependency(%q<httparty>.freeze, [">= 0"])
    s.add_dependency(%q<json>.freeze, [">= 2.0"])
    s.add_dependency(%q<multi_xml>.freeze, [">= 0.5.2"])
    s.add_dependency(%q<rdoc>.freeze, [">= 4.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<test-unit>.freeze, [">= 0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<webmock>.freeze, [">= 0"])
    s.add_dependency(%q<coveralls>.freeze, [">= 0"])
  end
end

